// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgpZIubVhI3JFkkq0h2KsAb7vhf7l9LWU',
    appId: '1:388637855338:web:cc7fed7e36725613690413',
    messagingSenderId: '388637855338',
    projectId: 'safeboard-28745',
    authDomain: 'safeboard-28745.firebaseapp.com',
    storageBucket: 'safeboard-28745.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqxwD7GoSY0vet4of7unSqC32OyEbhM4',
    appId: '1:388637855338:android:86b1f5ca8631a1fb690413',
    messagingSenderId: '388637855338',
    projectId: 'safeboard-28745',
    storageBucket: 'safeboard-28745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4JXoEJMIXoR5d4U-dOrCd30BKwxhvefA',
    appId: '1:388637855338:ios:29451f173820044a690413',
    messagingSenderId: '388637855338',
    projectId: 'safeboard-28745',
    storageBucket: 'safeboard-28745.firebasestorage.app',
    iosBundleId: 'com.nsbm.safeboard.safeboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4JXoEJMIXoR5d4U-dOrCd30BKwxhvefA',
    appId: '1:388637855338:ios:29451f173820044a690413',
    messagingSenderId: '388637855338',
    projectId: 'safeboard-28745',
    storageBucket: 'safeboard-28745.firebasestorage.app',
    iosBundleId: 'com.nsbm.safeboard.safeboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgpZIubVhI3JFkkq0h2KsAb7vhf7l9LWU',
    appId: '1:388637855338:web:f7cd9a1cba219879690413',
    messagingSenderId: '388637855338',
    projectId: 'safeboard-28745',
    authDomain: 'safeboard-28745.firebaseapp.com',
    storageBucket: 'safeboard-28745.firebasestorage.app',
  );
}
